before_install:
    - nvm install node
    - npm install -g gulp
    - npm install -g bower
install:
    - pip install -r requirements.txt
    - npm install
    - bower install
    - gulp build-app
script: 
    - python manage.py db init
    - python manage.py db upgrade
