language: python
python:
    - "2.7"
    - "3.5"
    - "nightly"
before_install:
    - nvm install node
    - npm install -g gulp
    - npm install -g bower
install:
    - pip install -r requirements.txt
    - npm install
    - bower install
    - gulp build-app
script: 
    - python manage.py db init
    - python manage.py db upgrade
    - python manage.py lint -f
    - python manage.py test
    - gulp jshint
cache:
    - pip
    directories:
        - node_modules # NPM packages
        - app/static/libs # Bower packages
notifications:
      slack: dirtyspacepirates:w02cmaNBga3UOhRAe4Mx3NRf
